
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PC RPL - R1
 */
public class modul10 extends javax.swing.JFrame {

    /**
     * Creates new form modul10
     */
    public modul10() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eData1 = new javax.swing.JTextField();
        eData2 = new javax.swing.JTextField();
        eHasil = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JmenuBar1 = new javax.swing.JMenuBar();
        menFile = new javax.swing.JMenu();
        menProses = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        meltBersih = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        meltPersegi = new javax.swing.JMenuItem();
        meltPersegiPanjang = new javax.swing.JMenuItem();
        meltSegitiga = new javax.swing.JMenuItem();
        meltLingkaran = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        meltPersegi2 = new javax.swing.JMenuItem();
        meltPersegiPanjang2 = new javax.swing.JMenuItem();
        meltSegitiga2 = new javax.swing.JMenuItem();
        meltLingkaran2 = new javax.swing.JMenuItem();
        menBantuan = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data 1");

        jLabel2.setText("Data 2");

        jLabel3.setText("Hasil");

        menFile.setText("File");
        JmenuBar1.add(menFile);

        menProses.setText("Proses");
        menProses.add(jSeparator1);

        meltBersih.setText("Bersih");
        meltBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltBersihActionPerformed(evt);
            }
        });
        menProses.add(meltBersih);

        jMenu1.setText("Luas");

        meltPersegi.setText("Persegi");
        meltPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltPersegiActionPerformed(evt);
            }
        });
        jMenu1.add(meltPersegi);

        meltPersegiPanjang.setText("Persegi Panjang");
        meltPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltPersegiPanjangActionPerformed(evt);
            }
        });
        jMenu1.add(meltPersegiPanjang);

        meltSegitiga.setText("Segitiga");
        meltSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltSegitigaActionPerformed(evt);
            }
        });
        jMenu1.add(meltSegitiga);

        meltLingkaran.setText("Lingkaran");
        meltLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltLingkaranActionPerformed(evt);
            }
        });
        jMenu1.add(meltLingkaran);

        menProses.add(jMenu1);

        jMenu2.setText("Keliling");

        meltPersegi2.setText("Persegi");
        meltPersegi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltPersegi2ActionPerformed(evt);
            }
        });
        jMenu2.add(meltPersegi2);

        meltPersegiPanjang2.setText("Persegi Panjang");
        meltPersegiPanjang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltPersegiPanjang2ActionPerformed(evt);
            }
        });
        jMenu2.add(meltPersegiPanjang2);

        meltSegitiga2.setText("Segitiga");
        meltSegitiga2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltSegitiga2ActionPerformed(evt);
            }
        });
        jMenu2.add(meltSegitiga2);

        meltLingkaran2.setText("Lingkaran");
        meltLingkaran2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltLingkaran2ActionPerformed(evt);
            }
        });
        jMenu2.add(meltLingkaran2);

        menProses.add(jMenu2);

        JmenuBar1.add(menProses);

        menBantuan.setText("Bantuan");
        JmenuBar1.add(menBantuan);

        setJMenuBar(JmenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(25, 25, 25)
                        .addComponent(eHasil))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(eData2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(eData1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eData2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meltBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltBersihActionPerformed
        eData1.setText("");
        eData2.setText("");
        eHasil.setText("");
    }//GEN-LAST:event_meltBersihActionPerformed

    private void meltPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltPersegiActionPerformed
         try {
            double sisi = Double.parseDouble(eData1.getText());
            double luas = sisi * sisi;
            eHasil.setText(String.valueOf(luas));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_meltPersegiActionPerformed

    private void meltPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltPersegiPanjangActionPerformed
        try {
            double panjang = Double.parseDouble(eData1.getText());
            double lebar = Double.parseDouble(eData2.getText());
            double luas = panjang * lebar;
            eHasil.setText(String.valueOf(luas));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_meltPersegiPanjangActionPerformed

    private void meltLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltLingkaranActionPerformed
        // TODO add your handling code here:
         try {
            double radius = Double.parseDouble(eData1.getText());
            double luas = Math.PI * radius * radius;
            eHasil.setText(String.valueOf(luas));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_meltLingkaranActionPerformed

    private void meltSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltSegitigaActionPerformed
        // TODO add your handling code here:
         try {
            double alas = Double.parseDouble(eData1.getText());
            double tinggi = Double.parseDouble(eData2.getText());
            double luas = 0.5 * alas * tinggi;
            eHasil.setText(String.valueOf(luas));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_meltSegitigaActionPerformed

    private void meltPersegi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltPersegi2ActionPerformed
        // TODO add your handling code here:
        try {
            double sisi = Double.parseDouble(eData1.getText());
            double keliling = 4 * sisi;
            eHasil.setText(String.valueOf(keliling));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_meltPersegi2ActionPerformed

    private void meltPersegiPanjang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltPersegiPanjang2ActionPerformed
        // TODO add your handling code here:
         try {
            double panjang = Double.parseDouble(eData1.getText());
            double lebar = Double.parseDouble(eData2.getText());
            double keliling = 2 * (panjang + lebar);
            eHasil.setText(String.valueOf(keliling));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_meltPersegiPanjang2ActionPerformed

    private void meltSegitiga2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltSegitiga2ActionPerformed
        // TODO add your handling code here:
        try {
            double sisi1 = Double.parseDouble(eData1.getText());
            double sisi2 = Double.parseDouble(eData2.getText());
            double sisi3 = Double.parseDouble(JOptionPane.showInputDialog("Masukkan sisi ketiga:"));
            double keliling = sisi1 + sisi2 + sisi3;
            eHasil.setText(String.valueOf(keliling));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_meltSegitiga2ActionPerformed

    private void meltLingkaran2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltLingkaran2ActionPerformed
        // TODO add your handling code here:
        try {
            double radius = Double.parseDouble(eData1.getText());
            double keliling = 2 * Math.PI * radius;
            eHasil.setText(String.valueOf(keliling));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_meltLingkaran2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modul10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modul10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modul10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modul10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modul10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar JmenuBar1;
    private javax.swing.JTextField eData1;
    private javax.swing.JTextField eData2;
    private javax.swing.JTextField eHasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem meltBersih;
    private javax.swing.JMenuItem meltLingkaran;
    private javax.swing.JMenuItem meltLingkaran2;
    private javax.swing.JMenuItem meltPersegi;
    private javax.swing.JMenuItem meltPersegi2;
    private javax.swing.JMenuItem meltPersegiPanjang;
    private javax.swing.JMenuItem meltPersegiPanjang2;
    private javax.swing.JMenuItem meltSegitiga;
    private javax.swing.JMenuItem meltSegitiga2;
    private javax.swing.JMenu menBantuan;
    private javax.swing.JMenu menFile;
    private javax.swing.JMenu menProses;
    // End of variables declaration//GEN-END:variables
}
