/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul2;

import javax.swing.JOptionPane;

/**
 *
 * @author PC RPL - R1
 */
public class modul2 extends javax.swing.JFrame {

    /**
     * Creates new form modul2
     */
    public modul2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNIM = new javax.swing.JLabel();
        jNAMA = new javax.swing.JLabel();
        eNIM = new javax.swing.JTextField();
        eNAMA = new javax.swing.JTextField();
        eCLEAR = new javax.swing.JButton();
        eEXIT = new javax.swing.JButton();
        eSAVE = new javax.swing.JButton();
        jALAMAT = new javax.swing.JLabel();
        eALAMAT = new javax.swing.JTextField();
        jNOTEP = new javax.swing.JLabel();
        eNOTEP = new javax.swing.JTextField();
        jSNIMNAMA = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dNIM = new javax.swing.JLabel();
        dNAMA = new javax.swing.JLabel();
        dALAMAT = new javax.swing.JLabel();
        jALL = new javax.swing.JButton();
        nTF1 = new javax.swing.JTextField();
        nTF2 = new javax.swing.JTextField();
        nTF3 = new javax.swing.JTextField();
        nTF4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jNIM.setText("NIM");

        jNAMA.setText("NAMA");

        eNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eNIMActionPerformed(evt);
            }
        });

        eNAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eNAMAActionPerformed(evt);
            }
        });

        eCLEAR.setText("CLEAR");
        eCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eCLEARActionPerformed(evt);
            }
        });

        eEXIT.setText("EXIT");
        eEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eEXITActionPerformed(evt);
            }
        });

        eSAVE.setText("SHOW");
        eSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eSAVEActionPerformed(evt);
            }
        });

        jALAMAT.setText("ALAMAT");

        jNOTEP.setText("NO TELEPON");

        jSNIMNAMA.setText("S NIM & NAMA");
        jSNIMNAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSNIMNAMAActionPerformed(evt);
            }
        });

        jLabel1.setText("2024-8-7");

        jALL.setText("S ALL");
        jALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jALLActionPerformed(evt);
            }
        });

        nTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nTF1ActionPerformed(evt);
            }
        });

        nTF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nTF4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eNOTEP)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNOTEP)
                            .addComponent(jALAMAT)
                            .addComponent(jNAMA)
                            .addComponent(jNIM)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSNIMNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dNIM)
                                .addGap(24, 24, 24)
                                .addComponent(dNAMA)
                                .addGap(18, 18, 18)
                                .addComponent(dALAMAT))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(eSAVE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(eCLEAR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jALL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(eEXIT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nTF4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(eALAMAT)
                    .addComponent(eNAMA)
                    .addComponent(eNIM))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jNIM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jNAMA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jALAMAT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNOTEP)
                .addGap(8, 8, 8)
                .addComponent(eNOTEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSNIMNAMA)
                    .addComponent(dNIM)
                    .addComponent(dNAMA)
                    .addComponent(dALAMAT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eSAVE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eCLEAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jALL)
                    .addComponent(nTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nTF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eEXIT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eNAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eNAMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eNAMAActionPerformed

    private void eNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eNIMActionPerformed

    private void eEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eEXITActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_eEXITActionPerformed

    private void eCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eCLEARActionPerformed
        // TODO add your handling code here:
        eNIM.setText("");
        eNAMA.setText("");
        eALAMAT.setText("");
        eNOTEP.setText("");
        dNIM.setText("");
        dNAMA.setText("");
        dALAMAT.setText("");
        nTF1.setText("");
        nTF2.setText("");
        nTF3.setText("");
        nTF4.setText("");
    }//GEN-LAST:event_eCLEARActionPerformed

    private void eSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eSAVEActionPerformed
        // TODO add your handling code here:
            String NIM = eNIM.getText();
            String NAMA = eNAMA.getText();
            String ALAMAT = eALAMAT.getText();
            String NOTEP = eNOTEP.getText();

            // Menampilkan hasil input
            JOptionPane.showMessageDialog(null, "NIM: " + NIM + "\nNAMA: " + NAMA + "\nALAMAT: " + ALAMAT + "\nNOTEP: " + NOTEP, "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_eSAVEActionPerformed

    private void jSNIMNAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSNIMNAMAActionPerformed
        // TODO add your handling code here:
          String NIM = eNIM.getText();
          String NAMA = eNAMA.getText();
          String ALAMAT = eALAMAT.getText();
          
          dNIM.setText(NIM);
          dNAMA.setText(NAMA);
          dALAMAT.setText(ALAMAT);
    }//GEN-LAST:event_jSNIMNAMAActionPerformed

    private void nTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nTF1ActionPerformed

    private void nTF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nTF4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nTF4ActionPerformed

    private void jALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jALLActionPerformed
        // TODO add your handling code here:
         String NIM = eNIM.getText();
         String NAMA = eNAMA.getText();
         String ALAMAT = eALAMAT.getText();
         String NOTEP = eNOTEP.getText();
         
         nTF1.setText(NIM);
         nTF2.setText(NAMA);
         nTF3.setText(ALAMAT);
         nTF4.setText(NOTEP);
    }//GEN-LAST:event_jALLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modul2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modul2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modul2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modul2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modul2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dALAMAT;
    private javax.swing.JLabel dNAMA;
    private javax.swing.JLabel dNIM;
    private javax.swing.JTextField eALAMAT;
    private javax.swing.JButton eCLEAR;
    private javax.swing.JButton eEXIT;
    private javax.swing.JTextField eNAMA;
    private javax.swing.JTextField eNIM;
    private javax.swing.JTextField eNOTEP;
    private javax.swing.JButton eSAVE;
    private javax.swing.JLabel jALAMAT;
    private javax.swing.JButton jALL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jNAMA;
    private javax.swing.JLabel jNIM;
    private javax.swing.JLabel jNOTEP;
    private javax.swing.JButton jSNIMNAMA;
    private javax.swing.JTextField nTF1;
    private javax.swing.JTextField nTF2;
    private javax.swing.JTextField nTF3;
    private javax.swing.JTextField nTF4;
    // End of variables declaration//GEN-END:variables
}
